spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/shortenerdb
    username: shorteneruser
    password: shortenerpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080